name = "Rconversion"
uuid = "bd662e70-62b3-4b91-86dc-3d667c30a415"
version = "1.0.0-DEV"
authors = ["Douglas Bates <dmbates@gmail.com> and contributors"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataFrames = "1.8.1"
DataStructures = "0.19.1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
