name = "Rconversion"
uuid = "bd662e70-62b3-4b91-86dc-3d667c30a415"
authors = ["Douglas Bates <dmbates@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
